In [1]:
import pandas as pd
import numpy as np
import seaborn as sns
import matplotlib.pyplot as plt

In [47]:

df = pd.DataFrame({
    "name": ["Ali", "Ali", "Omar", "Moussa"],
    "age": [20, 25, 30, 35],
    "city": ["Bamako", "Paris", "Dakar", "Lyon"]
})

df

     name  age    city
0     Ali   20  Bamako
1     Ali   25   Paris
2    Omar   30   Dakar
3  Moussa   35    Lyon

In [82]:
df.to_csv("../data/data.csv", index=False)

In [48]:
df[df["name"]=="Ali"].head(1)

  name  age    city
0  Ali   20  Bamako

In [ ]:
df.loc[((df["name"]=="Ali") & (df["age"]>25)),['name','age']]="Abba",55
df.head()

     name  age    city
0     Ali   20  Bamako
1     Ali   25   Paris
2    Omar   30   Dakar
3  Moussa   35    Lyon

In [50]:
df.replace({"Abba":"Jean","Moussa":"Paul"})

   name  age    city
0   Ali   20  Bamako
1   Ali   25   Paris
2  Omar   30   Dakar
3  Paul   35    Lyon

In [51]:
print(df.name=="Ali")

0     True
1     True
2    False
3    False
Name: name, dtype: bool

In [63]:
df[df.name=="Ali"].index

RangeIndex(start=0, stop=2, step=1)